/* Generated By:JavaCC: Do not edit this line. HILParserConstants.java */
package vpc.hil.parser;

public interface HILParserConstants {

    int KW_DEVICE = 13;
    int KW_INTERRUPT = 14;
    int KW_REGISTER = 16;
    int KW_INSTRUCTION = 17;
    int KW_REGION = 18;
    int KW_SPACE = 19;
    int DECIMAL_LITERAL = 20;
    int HEX_LITERAL = 21;
    int BIN_LITERAL = 22;
    int IDENTIFIER = 23;
    int TK_LPAREN = 26;
    int TK_RPAREN = 27;
    int TK_LBRACE = 28;
    int TK_RBRACE = 29;
    int TK_LBRACKET = 30;
    int TK_RBRACKET = 31;
    int TK_SEMI = 32;
    int TK_ELLIPSIS = 33;
    int TK_ASSIGN = 34;
    int TK_COLON = 35;

    String[] tokenImage = {"<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"", "\"//\"", "<token of kind 7>", "\"/*\"", "<SINGLE_LINE_COMMENT>", "\"*/\"", "\"*/\"", "<token of kind 12>", "\"device\"", "\"interrupt\"", "\"masks\"", "\"register\"", "\"instruction\"", "\"region\"", "\"space\"", "<DECIMAL_LITERAL>", "<HEX_LITERAL>", "<BIN_LITERAL>", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"(\"", "\")\"", "\"{\"", "\"}\"", "\"[\"", "\"]\"", "\";\"", "\"...\"", "\"=\"", "\":\"",};

}
