/* Generated By:JavaCC: Do not edit this line. Virgil3ParserConstants.java */
package vpc.vst.parser.v3;

public interface Virgil3ParserConstants {

    int KW_BREAK = 13;
    int KW_CLASS = 14;
    int KW_COMPONENT = 15;
    int KW_CONTINUE = 16;
    int KW_ELSE = 17;
    int KW_EXTENDS = 18;
    int KW_FIELD = 19;
    int KW_IF = 20;
    int KW_LOCAL = 21;
    int KW_METHOD = 22;
    int KW_NEW = 23;
    int KW_PRIVATE = 24;
    int KW_RETURN = 25;
    int KW_SUPER = 26;
    int KW_MATCH = 27;
    int KW_THIS = 28;
    int KW_WHILE = 29;
    int KW_VALUE = 30;
    int KW_PROGRAM = 31;
    int KW_ENTRYPOINT = 34;
    int KW_FALSE = 35;
    int KW_TRUE = 36;
    int KW_NULL = 37;
    int ZERO_LITERAL = 38;
    int DECIMAL_LITERAL = 39;
    int HEX_LITERAL = 40;
    int BIN_LITERAL = 41;
    int OCTAL_LITERAL = 42;
    int CHARACTER_LITERAL = 43;
    int STRING_LITERAL = 44;
    int IDENTIFIER = 45;
    int TK_LPAREN = 48;
    int TK_RPAREN = 49;
    int TK_LBRACE = 50;
    int TK_RBRACE = 51;
    int TK_LBRACKET = 52;
    int TK_RBRACKET = 53;
    int TK_SEMI = 54;
    int TK_COMMA = 55;
    int TK_DOT = 56;
    int TK_ASSIGN = 57;
    int TK_COND_AND = 58;
    int TK_COND_OR = 59;
    int TK_ARROW = 60;
    int TK_LT = 61;
    int TK_GT = 62;
    int TK_LTEQ = 63;
    int TK_GTEQ = 64;
    int TK_SHL = 65;
    int TK_SHR = 66;
    int TK_NOT = 67;
    int TK_COLON = 68;
    int TK_TYPE_QUERY = 69;
    int TK_TYPE_CAST = 70;
    int TK_EQ = 71;
    int TK_PLUS = 72;
    int TK_MINUS = 73;
    int TK_MUL = 74;
    int TK_AND = 75;
    int TK_OR = 76;
    int TK_XOR = 77;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"//\"",
            "<token of kind 7>",
            "\"/*\"",
            "<SINGLE_LINE_COMMENT>",
            "\"*/\"",
            "\"*/\"",
            "<token of kind 12>",
            "\"break\"",
            "\"class\"",
            "\"component\"",
            "\"continue\"",
            "\"else\"",
            "\"extends\"",
            "\"field\"",
            "\"if\"",
            "\"local\"",
            "\"method\"",
            "\"new\"",
            "\"private\"",
            "\"return\"",
            "\"super\"",
            "\"match\"",
            "\"this\"",
            "\"while\"",
            "\"value\"",
            "\"program\"",
            "\"type\"",
            "\"module\"",
            "\"entrypoint\"",
            "\"false\"",
            "\"true\"",
            "\"null\"",
            "\"0\"",
            "<DECIMAL_LITERAL>",
            "<HEX_LITERAL>",
            "<BIN_LITERAL>",
            "<OCTAL_LITERAL>",
            "<CHARACTER_LITERAL>",
            "<STRING_LITERAL>",
            "<IDENTIFIER>",
            "<LETTER>",
            "<DIGIT>",
            "\"(\"",
            "\")\"",
            "\"{\"",
            "\"}\"",
            "\"[\"",
            "\"]\"",
            "\";\"",
            "\",\"",
            "\".\"",
            "\"=\"",
            "\"&&\"",
            "\"||\"",
            "\"->\"",
            "\"<\"",
            "\">\"",
            "\"<=\"",
            "\">=\"",
            "\"#<<\"",
            "\"#>>\"",
            "\"!\"",
            "\":\"",
            "\"<:\"",
            "\"::\"",
            "<TK_EQ>",
            "\"+\"",
            "\"-\"",
            "<TK_MUL>",
            "\"&\"",
            "\"|\"",
            "\"^\"",
            "\"=>\"",
    };

}
